name: Test Conditional Workflow

on: 
  pull_request:
    paths-ignore:
      - '**/*.mk'

jobs:
  test-job1:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Check for .mk file changes
      id: check_changes
      run: |
        CHANGED_FILES=$(git diff --name-only ${{ github.base_ref }}...${{ github.head_ref }} | grep '\.mk$' || true)
        if [[ -z "$CHANGED_FILES" ]]; then
          echo "SHOULD_SKIP=false" >> $GITHUB_ENV
        else
          echo "SHOULD_SKIP=true" >> $GITHUB_ENV
         
  test-job2:
    runs-on: ubuntu-latest
    if: env.SHOULD_SKIP != 'true'
    steps:
    - uses: actions/checkout@v3

    - name: Conditional Step
      if: steps.check_changes.outputs.should_skip != 'true'
      run: |
        echo "This step is running because should_skip is not true."

    # 另一个条件步骤
    - name: Another Conditional Step
      if: steps.check_changes.outputs.should_skip != 'true'
      run: |
        echo "This is another step that is only running because should_skip is not true."
